### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by aviatesk** [aviatesk/JET.jl#121]
Deadline: 2021/04/01

TODO:
- [x] stabilize API (mainly, give consistent naming for entry points, decide which/when to use `analyze/profile/report`)
- [x] setup documentation
  * [x] usage
  * [x] internals
- [x] tag v0.1

**Comment by PallHaraldsson** [comment]
Hi, since I see all checked except for just tagging, could it be done?

More importantly is if too soon to promote this package? I get asked if such as available, and I hesitate as it's experimental and not registered.

It seems to work in the just released Julia 1.6, with some minor issues (hangs in the end, and repeats):

```
julia> report_and_watch_file("demo.jl"; annotate_types = true)
[toplevel-info] entered into demo.jl
[toplevel-info]  exited from demo.jl (took 5.622 sec)
[..]
││┌ @ operators.jl:328 Base.<(x::String, y::Int64)
[..]
[toplevel-info]  exited from demo.jl (took 0.037 sec)
```

**Comment by aviatesk** [comment]
@PallHaraldsson sorry for the delay. I will work on the release this weekend.

**Comment by aviatesk** [comment]
https://github.com/JuliaRegistries/General/pull/33580
