### ISSUE TITLE
Report linting errors using Julia's `Logging` stdlib...

### ISSUE THREAD

**Issue by adamslc** [aviatesk/JET.jl#171]
...or at least have the option to. The motivation here is that it is very easy to work with logging records, which makes it easier to create new printing/interaction methods. I'm particularly interested in generating GitHub annotations from `JET.jl` results. See [here](https://github.com/adamslc/JuliaGHA.jl/pull/5/files) for an example of what annotations look like for test failures.

**Comment by aviatesk** [comment]
Could you tell me how do you want to use JET (maybe with an example snippet or something), please ?
I'm not sure how JET's current API (i.e. `report_xxx(io::IO, ...)` or `analyze_xxx(...)`) is not enough for your use case.

**Comment by adamslc** [comment]
Sure, if you look at
https://github.com/adamslc/JuliaGHA.jl/pull/5/files#file-test-runtests-jl-L16,
you should see a GitHub annotation indicating that the test failed. To do this, I am using a modified `@testset` that reports test failures as log messages rather than printing to `stderr`. Those messages can then be consumed, and turned into GitHub annotations.

If `JET.jl` also produced log messages, then the same thing could be done with the linting results. The goal of this is to surface testing failures into the GitHub UI (instead of hidden in a log file), which I think will improve the accessibility of submitting PRs.

**Comment by aviatesk** [comment]
hm, why do you need to use functionalities of `Logging` module ?
Just using something like
```julia
out = IOBuffer() # or whatever IO
report_file(out, yourfile)
s = String(take!(out))
# render `s` or whatever
```
won't suffice ? (still I think you will want to use `analyse_xxx`, which allows you to directly interact with errors collected by JET)

**Comment by adamslc** [comment]
You're right that I could simply parse the output from this log in the way you suggest:
https://github.com/adamslc/JuliaGHA.jl/pull/5/checks?check_run_id=2392399247
However, it seems like an unnecessary amount of work to "stringify" the linting errors, only to parse them back into Julia to create the annotations. 

You shouldn't feel obligated to work on this, but I do think that some more general output format will eventually be needed for interop with IDEs. Perhaps this sort of output would be more natural to add when that system has been designed.

**Comment by aviatesk** [comment]
Okay, so I think you want to interact with the result of `analyze_xxx`, rather than `report_xxx` entries.
For example `JET.analyze_file` returns `res::JET.VirtualProcessResult`, and you can implement a frontend code to render `res.toplevel_error_reports::Vector{JET.ToplevelErrorReport}` or `res.inference_error_reports::Vector{JET.InferenceErrorReport}` in GitHub annotations.
Go ahead for [the documentation of JET's report interface](https://aviatesk.github.io/JET.jl/dev/internals/#Error-Report-Interface), which should explain the API of JET's error reports (but please don't hesitate to ask questions, I just wrote the documentation this morning and it's not really matured).
For the frontend implementation, you may want to reuse JET's frontend code (those defined in [print.jl](https://github.com/aviatesk/JET.jl/blob/92c7a6902bea06a2cffcf400370d6e41e48301ea/src/print.jl) to render error reports in `io::IO`).

**Comment by adamslc** [comment]
That looks like exactly what I need! Thanks for taking the time to point it out. Sorry that I hadn't understood the difference between `report_*` and `analyze_*` earlier.

**Comment by aviatesk** [comment]
You're welcome, looking forward to your application :) That should be very useful.

**Comment by aviatesk** [comment]
This is now well documented: https://aviatesk.github.io/JET.jl/dev/internals/#Analysis-Results
