### ISSUE TITLE
Feature request: Throw on unknown kwarg

### ISSUE THREAD

**Issue by jakobnissen** [aviatesk/JET.jl#414]
Currently, you can do
```julia
julia> report_call(+, (Int, Int), lkdsjkdlkas=true)
No errors detected
```
Which is not very bad - but it's a little annoying when it looks like this:
```
julia> @report_call target_module=(Core,) sum(Char[])
═════ 2 possible errors found ═════
[ errors elided ]
```
Wait, this actually can error in `Core`? Not really - but I misspelled `target_modules` as `target_module`.

I think it would be nicer if JET's functions threw an error if they got unknown kwargs

**Comment by aviatesk** [comment]
Yes, this weird behavior is because of an implementation detail of JET (i.e. I wanted to passing down `; kwargs...` to all subroutines rather than writing down every keyword options), e.g. https://github.com/aviatesk/JET.jl/blob/14ce2c83bbf4b932bad8469971b30badcd300e96/src/abstractinterpret/abstractanalyzer.jl#L246-L254

There might be some solutions, like 
```julia
    validate_kwargs!(__jetconfigs...) # check if there is any invalid option passed down here
    return InferenceParams(; ...)
```
