### ISSUE TITLE
Document filtering better

### ISSUE THREAD

**Issue by jakobnissen** [aviatesk/JET.jl#415]
It's not quite clear to me exactly how filtering works - i.e. how it's supposed to be used by a user. Is it correct that:

* You can use `target_modules=` or `ignored_modules=`. The former makes the result ONLY includes errors where the error is thrown in any of the modules, the latter removes all errors where the error is thrown in that module
* You can also use `target_modules=(AnyFrameModule(x),)` (or same for `ignore_modules`), which filters for/away the error if any stack frame in the callchain originates from that module.

If so, why doesn't this show an error?
```
julia> module ModA
       f(x::Int) = x + 1
       end;

julia> module ModB
       using ..ModA: f
       g(x) = f(x)
       end;

julia> @report_call target_modules=(AnyFrameModule(ModA),) ModB.g("a")
No errors detected
```

* How does `frame_filter` work?

**Comment by aviatesk** [comment]
First of all sorry but I just recognized that the documentation for this sort of stuff has been broken in recent versions. Now it should be fixed, please refer to https://aviatesk.github.io/JET.jl/dev/config/#result-config .

I will respond to your original questions in the following replay.

**Comment by aviatesk** [comment]
> * You can use `target_modules=` or `ignored_modules=`. The former makes the result ONLY includes errors where the error is thrown in any of the modules, the latter removes all errors where the error is thrown in that module

Yes. In more details, they are true when `target_modules=`/`ignored_modules` are specified as iterator of `Module` object or `JET.LastFrameModule` object.

> * You can also use `target_modules=(AnyFrameModule(x),)` (or same for `ignore_modules`), which filters for/away the error if any stack frame in the callchain originates from that module.

You're right.

> If so, why doesn't this show an error?

This is a bit tricky, but for this specific case, the actual error is happen within the context of `ModB` rather than `ModA`, since the error is a dispatch error which happens at a call of `f(::String)`, but not within a call of `f(::String)` (which is impossible to happen).
So for this case, `ModB` is where the error is thrown, so analysis doesn't further steps into anything related to `ModA`.


> * How does `frame_filter` work?

There is no longer `frame_filter` configuration. JET had it, but it's generalized to `target_modules` and `ignored_modules` configurations. [This extendable analysis example](https://aviatesk.github.io/JET.jl/dev/generated-plugin-examples/dispatch_analysis/) implements it, but it is just because this example hasn't been updated recently.

**Comment by jakobnissen** [comment]
Okay thanks! I'm preparing a few PRs to the docs and README of JET and wanted to make sure I got these things right

**Comment by aviatesk** [comment]
Great, that's very exciting! I'm very looking forward to your PRs!
