### ISSUE TITLE
Line numbers do not Revise

### ISSUE THREAD

**Issue by timholy** [aviatesk/JET.jl#513]
When writing out a report, the numbers appear to reflect the line number at the last time the method was defined, not the current line number in a file you might have made changes to. The `whereis` method of CodeTracking allows you to offset the line numbers when you report.

**Comment by aviatesk** [comment]
So it looks like Revise is able to change the line number information of a method that has been moved without redefining it? Since JET records and caches those line information (that is invalidated upon method invalidation), JET shows a staled stacktrace-like view in a case when Revise updated method information without redefining it.

Could you give me any pointer on how/where Revise updates method information without redefining it? I think we can update JET's cache information using a callback.

**Comment by timholy** [comment]
You can use `whereis`, it reports the updated line info. You can see the implementation here: https://github.com/timholy/CodeTracking.jl/blob/bf0a1efb6d64f0123d3b91b0dccb8d4e62fa8659/src/CodeTracking.jl#L70-L90
but I think it's better to just use `whereis` if you can.
